# Evaluation Pipeline

Here, I am implementing the metrices used for evaluating the evaluation quality

In [1]:
#imports 

import os
import sys

path_to_add = os.path.abspath(os.path.join(os.getcwd(), '..'))
if path_to_add not in sys.path:
    sys.path.append(path_to_add)


import numpy as np
import pandas as pd
import pickle

from Utilities.utilities import *
from Utilities.lime_segmentation import *
from Utilities.xai_evaluation import *

2024-02-19 20:15:02.065215: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-02-19 20:15:02.065271: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/pknab/miniconda3/envs/envi/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
date_path = "FEL_VIT"

dataset_path = "../Dataset/Results/"+date_path+"/eval_results.pkl"
    
dataset = pickle.load(open(dataset_path, "rb"))

small_dataset= get_small_eval_dictionary(dataset)

In [3]:
lime_names = ["DSEG", "BayesLime", "SLIME", "GLIME", "LIME"]
images = np.unique(list((small_dataset.keys())))
for i in small_dataset.keys():
    domains = np.unique(list((small_dataset[i].keys())))
sorted_dictionary = {}

ground_truths = []
groundtruth_test = []

for local_domain in domains:
    sorted_dictionary[local_domain] = {}
    for local_image in images:
        for in_keys in list(small_dataset[local_image]["groundtruth"].keys()):
            if "ground" in in_keys.lower():
                ground_truths.append(small_dataset[local_image]["groundtruth"][in_keys][1])
            break
        for in_keys in list(small_dataset[local_image]["contrastivity"].keys()):
            if "groundtruth_test" in in_keys.lower():
                groundtruth_test.append(small_dataset[local_image]["contrastivity"][in_keys][1])
            break
        for local_name in small_dataset[local_image][local_domain].keys():
            #print(small_dataset[local_image])
            if local_image not in sorted_dictionary[local_domain].keys():
                sorted_dictionary[local_domain][local_image] = {}
            for local_metric in lime_names:
                if local_metric.lower() not in sorted_dictionary[local_domain][local_image].keys():
                    sorted_dictionary[local_domain][local_image][local_metric.lower()] = {}
            for local_metric in lime_names:
                if local_metric.lower() in local_name.lower():
                    sorted_dictionary[local_domain][local_image][local_metric.lower()][local_name] = small_dataset[local_image][local_domain][local_name]
                    
                    break


final_dict = {}
order_images = []
for i in list(sorted_dictionary.keys()):
    for domain in list(sorted_dictionary[i].keys()):
        domain_dict = {}
        local_dictionary = sorted_dictionary[i]
        for j in local_dictionary.keys():
            local_dict = local_dictionary[j]
            for k in local_dict.keys():
                if k not in domain_dict.keys():
                    domain_dict[k] = {}
                local_dict_ = local_dict[k]
                for l in local_dict_.keys():
                    if l not in domain_dict[k].keys():
                        domain_dict[k][l] = []
                    domain_dict[k][l].append(local_dict_[l])
                    
        final_dict[i] = domain_dict
    
eval_dict = {}
for i in final_dict.keys():
    local_df = {}
    for j in final_dict[i].keys():
        for k in final_dict[i][j].keys():
            if len(np.array(final_dict[i][j][k]).shape) == 2:
                if "preservation_noise" in k:
                    local_df[k] = 0
                    for num, data in enumerate(final_dict[i][j][k]):
                        if data[1] == ground_truths[num]:
                            local_df[k] += 1
                elif "deletion_noise" in k:
                    local_df[k] = 0
                    for num, data in enumerate(final_dict[i][j][k]):
                        if data[1] != ground_truths[num]:
                            local_df[k] += 1
                
                elif "preservation_check_contrast" in k:
                    local_df[k] = 0
                    for num, data in enumerate(final_dict[i][j][k]):
                        if data[1] == groundtruth_test[num]:
                            local_df[k] += 1
                elif "deletion_check_contrast" in k:
                    local_df[k] = 0
                    for num, data in enumerate(final_dict[i][j][k]):
                        if data[1] != groundtruth_test[num]:
                            local_df[k] += 1
                
                elif "preservation" in k:
                    local_df[k] = 0
                    for num, data in enumerate(final_dict[i][j][k]):
                        if data[1] == ground_truths[num]:
                            local_df[k] += 1

                elif "single_deletion" in k:
                    local_df[k] = 0
                    for num, data in enumerate(final_dict[i][j][k]):
                        if data[1] == ground_truths[num]:
                            local_df[k] += 1
                elif "deletion" in k:
                    local_df[k] = 0
                    for num, data in enumerate(final_dict[i][j][k]):
                        if data[1] != ground_truths[num]:
                            local_df[k] += 1
                elif "model_random" in k:
                    local_df[k] = 0
                    for num, data in enumerate(final_dict[i][j][k]):
                        if data[1] != ground_truths[num]:
                            local_df[k] += 1
                elif "eval_random" in k:
                    local_df[k] = 0
                    for num, data in enumerate(final_dict[i][j][k]):
                        if data[1] != ground_truths[num]:
                            local_df[k] += 1
            else:
                try:
                    local_df[k] = np.mean(final_dict[i][j][k])
                except:
                    pass
                
    eval_dict[i] = local_df

def dataframe_results(data):
    df = pd.DataFrame(data.items(), columns=['Metric', 'Value'])

    # Splitting the 'Metric' column to extract additional categorical information
    df[['Method', 'Metric_Type']] = df['Metric'].str.split('_', n=1, expand=True)

    # Drop the original 'Metric' column as its information has been extracted
    df.drop('Metric', axis=1, inplace=True)

    # Reordering the columns for better readability
    df = df[['Method', 'Metric_Type', 'Value']]

    df_pivot = df.pivot(index='Metric_Type', columns='Method', values='Value')

    # Display the pivoted DataFrame
    return df_pivot
    
eval_dict.keys()

dict_keys(['consistency', 'contrastivity', 'correctness', 'groundtruth', 'output_completness'])

## Overview

In [4]:
dataframe_results(eval_dict["groundtruth"])

Method       BayesLIME       DSEG     GLIME       LIME      SLIME
Metric_Type
segments     19.050000  16.400000  19.05000  19.050000  19.050000
time         18.587775  67.994975  16.26973  20.444025  15.560055

In [5]:
df_color = ColoredDF()
df_color.create_pandas_plot(small_dataset, to_save_path = './Dataset/Results/'+date_path+'/', id = 0)

## Correctness

In [6]:
dataframe_results(eval_dict["correctness"])

Method,BayesLIME,DSEG,GLIME,LIME,SLIME
Metric_Type,,,,,
Compactness,0.123305,0.154170,0.127145,0.126935,0.123315
incremental_deletion,0.390470,0.127955,0.318735,0.361945,0.373785
prediction_eval_random,19.000000,17.000000,19.000000,20.000000,18.000000
prediction_model_random,19.000000,19.000000,19.000000,19.000000,19.000000
prediction_single_deletion,4.000000,7.000000,5.000000,4.000000,4.000000

In [7]:
df_color.create_pandas_plot(small_dataset, to_save_path = './Dataset/Results/'+date_path+'/', id = 1)

## Contrastivity

In [8]:
dataframe_results(eval_dict["contrastivity"])

Method                       BayesLIME  DSEG  GLIME  LIME  SLIME
Metric_Type
deletion_check_contrast              9    12      8     9      9
deletion_noise_check                10    15     10    10     10
preservation_check_contrast         10    10     10     9     10
preservation_noise_check             8    11      7     8      7
single_deletion                      6     7      6     6      6

In [9]:

df_color.create_pandas_plot(small_dataset, to_save_path = './Dataset/Results/'+date_path+'/', id = 2)

## Output Completenes

In [10]:
dataframe_results(eval_dict["output_completness"])

Method              BayesLIME  DSEG  GLIME  LIME  SLIME
Metric_Type
deletion_check             15    16     16    14     15
preservation_check          7     6      7     6      6

In [11]:
df_color.create_pandas_plot(small_dataset, to_save_path = './Dataset/Results/'+date_path+'/', id = 3)

## Consistency

In [12]:
dataframe_results(eval_dict["consistency"])

Method                    BayesLIME      DSEG     GLIME      LIME      SLIME
Metric_Type
deletion_noise_check       14.00000  17.00000  15.00000  14.00000  14.000000
preservation_noise_check    3.00000  10.00000   5.00000   4.00000   4.000000
stability                   0.01352   0.01266   0.01472   0.01383   0.013745

In [13]:
df_color.create_pandas_plot(small_dataset, to_save_path = './Dataset/Results/'+date_path+'/', id = 4)